### ISSUE TITLE
[wiki] stable or staging ?

### ISSUE THREAD

**Issue by malko42** [starcitizen-lug/information-howtos#1]
In the [quick start page](https://github.com/starcitizen-lug/information-howtos/wiki/Quick-Start-Guide), first step, we advise to install `wine-stable` but when following GE's post we end up installing `wine-staging`.
Which one is it ? Stable ? Staging ? Both ?

Also, is it wise to make people install & use DXVK async with EAC right around the corner ?

**Comment by beniwtv** [comment]
I changed the wine bit, I'd leave async for now, until we have more information about EAC.
