### ISSUE TITLE
Adding dxvk_state_cache to the wiki

### ISSUE THREAD

**Issue by chalybeum** [starcitizen-lug/information-howtos#2]
I'd like to suggest to add a paragraph about the state cache to our wiki.

Please see my proposed wording at following link:

https://github.com/chalybeum/information-howtos/wiki#lug-helper

**Comment by the-sane** [comment]
Is that DXVK state cache setting only for nVidia?

**Comment by the-sane** [comment]
Also, is it specifically for GL shaders?  What happens if both the nVidia and DXVK shader variables are set?  Which gets priority or does everything just explode?

**Comment by gort818** [comment]
GPU agnostic

`DXVK caches pipeline state by default, so that shaders can be recompiled ahead of time on subsequent runs of an application, even if the driver's own shader cache got invalidated in the meantime`

**Comment by gort818** [comment]
and DXVK state cache was well before 1.9.2

**Comment by the-sane** [comment]
I gotcha, so this is the same thing that Lutris already stores in `lutris/runtime/dxvk` then?

I don't see a need to specify it in our wiki when it already defaults to on and goes into a standard location.  The Helper already knows about that location and if people start putting it elsewhere, the Helper can't help them clear it anymore if they need to.

**Comment by gort818** [comment]
Don't know about lutris sorry I run it manually.

**Comment by chalybeum** [comment]
Allright, didn't know about the Lutris default. My bad.
