### ISSUE TITLE
Where are the "Special LUG Wine Builds below"?

### ISSUE THREAD

**Issue by matt32106** [starcitizen-lug/information-howtos#3]
The text says 
"As of 3.13 we recommend a runner built for Star Citizen - see Special LUG Wine Builds below"
but I don't see any link to a list of special builds. Where is it?

**Comment by beniwtv** [comment]
That should be: https://github.com/starcitizen-lug/information-howtos/wiki/Wine-Builds-for-Star-Citizen
(We're also moving them here to this GitHub org)

**Comment by matt32106** [comment]
Ok found it. Maybe add the link in the page?!

**Comment by beniwtv** [comment]
Just done it - this is still under construction here :)

**Comment by matt32106** [comment]
Great thanks!
