### ISSUE TITLE
how and where to add environment vars?

### ISSUE THREAD

**Issue by badbabykosh** [starcitizen-lug/information-howtos#4]
Greetings Programs.....not sure how to ask for an update to the wiki but here goes...on this page...https://github.com/starcitizen-lug/information-howtos/wiki/Performance-Tuning ... it mentions adding environment variables. It seems to assume the noob reader understands where and how? As a noob it would help to know how and in which file(s) I can do said adding. ^_^

**Comment by the-sane** [comment]
On it :+1: 

I fight for the users!

**Comment by the-sane** [comment]
Does this edit help explain it?
https://github.com/starcitizen-lug/information-howtos/wiki/Performance-Tuning

**Comment by badbabykosh** [comment]
The IO tower is lit!

**Comment by beniwtv** [comment]
We should add a screenshot to the page as well, as some users have been confused on what they need to add as "key" and "value" in that Lutris window.

**Comment by the-sane** [comment]
Done :+1:
