### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Gaming4LifeDE** [starcitizen-lug/information-howtos#5]
Hi. I wonder if it would be possible to package the correct wine/proton versions and a wrapper script for the launcher into a flatpak to make installation easier. Any ideas?

Also, I'm really on the fence about buying SC considering it might not even work on my system (Ryzen 5 2600x, 32gb RAM, RX590, Fedora). Would i mess up my Fedora install trying to get SC working?

**Comment by the-sane** [comment]
That's essentially what Lutris does if you follow our quick start guide, and this is the recommended installation method.  The only hiccup right now is the Lutris script still has the wrong runner name written in it but, unfortunately, we don't control that and can only ask them to fix it and wait.

I've asked for some feedback from our other Penguins on how well the game will run on those specs, but I suspect it'll be just fine. The game lives within its own wine prefix and you'll install one of our custom runners built specifically for the game, so you won't need to install anything natively on your system besides Lutris.  Undoing it all is a simple matter of deleting the prefix directory and uninstalling Lutris, no harm done.

**Comment by FRUiT-git** [comment]
My SC runs quite well on a i5 4690, 32GB RAM 1600 MHz, Asus  Geforce 1080 strix, ubuntu.

Combat is not always possible, and I go below 15 FPS in big towns, but overall it runs well for what I do in game (trading - mining - other missions).

Cheers !

**Comment by hsmalley** [comment]
I don't see you messing up for Fedora install by getting SC working. Lutris (and the LUG Helper) do all the hard work for you. I run Fedora too and can vouch that it works. As for system specs, yea it should run. Check out https://robertsspaceindustries.com/telemetry to get a better idea of how it will perform on your system.

**Comment by wwilliams** [comment]
sc should work fine on your system.
i was running it on a r7 2700x 32 gb ram and a rx480.

**Comment by Gaming4LifeDE** [comment]
Installing wine integrates into the system in a normal circumstance. Does
lutris do it different? And also, would flatpak also just be an easy option
for installation, wouldn't it?

FRUiT-git ***@***.***> schrieb am Mi., 22. Dez. 2021, 18:40:

**Comment by ananace** [comment]
I had no issue running SC with an i7-7700K, 16GB of RAM, and an RX580.

It's worth mentioning that a [Flatpak install of Lutris](https://github.com/flathub/net.lutris.Lutris) does just fine in regards to running Star Citizen as well, it's how I'm currently playing.

**Comment by the-sane** [comment]
Lutris uses runners, which are self-contained wine versions.  Our Helper downloads them for you and extracts them under the Lutris install directory. Then, Lutris uses them when launching the game. The runner isn't actually "installed" on your system, just extracted into a directory.  We have folks in our org compiling runners specifically optimized and tested for Star Citizen.

It's easier doing it this way than a flatpak because there are multiple runner/dxvk options and some work better than others depending on your hardware.  We try to make the whole process as easy as possible between Lutris and the LUG Helper script.  It's as close to a one-click solution as we can get right now.

**Comment by Gaming4LifeDE** [comment]
Hmm what would be so complicated with flatpak? I'd imagine some sort of
launcher which downloads everything and has a panel for options and tweaks.
Would it be too hard to implement the GUI? I'm eager to try GTK with python
but I don't really have any starting point so that might not be too bad.
Who knows, i really have no idea how the project structure and build system
used for GTK apps work.

the Sane. ***@***.***> schrieb am Mi., 22. Dez. 2021, 19:43:

**Comment by the-sane** [comment]
What you're describing is exactly how Lutris works :)

**Comment by Silvatech** [comment]
> Hi. I wonder if it would be possible to package the correct wine/proton versions and a wrapper script for the launcher into a flatpak to make installation easier. Any ideas?
> 
> Also, I'm really on the fence about buying SC considering it might not even work on my system (Ryzen 5 2600x, 32gb RAM, RX590, Fedora). Would i mess up my Fedora install trying to get SC working?

Your CPU is good. I have used that same CPU. 32GB fine as long as you can have a pagefile on an ssd. Well should run regardless. Also SSD is a must for the game itself. Just to large and slow otherwise. Only thing I don't know and maybe someone else can answer is your video card I have no experience using that card. Maybe someone else has tried that video card and can help you with that part.

**Comment by Gaming4LifeDE** [comment]
> What you're describing is exactly how Lutris works :)

I'd say it depends. Lutris is not really made for star citizen specifically where as a custom launcher would be. I don't know, I guess i just like the idea.

> Only thing I don't know and maybe someone else can answer is your video card I have no experience using that card

And that's exactly what's worrying me. It's a pretty slow card and I have 2 4k monitors connected. I'd set the resolution to 1080p because there's no way an RX590 would handle 4k but the upscaling costs performance too.

**Comment by the-sane** [comment]
> I'd say it depends. Lutris is not really made for star citizen specifically where as a custom launcher would be.

Regardless, the behavior you're describing of a launcher that downloads everything automatically and has a panel for settings and tweaks is how Lutris works with the Star Citizen install script.  You'll see what I mean when you go to install the game.  What you're asking for already exists, just not as a flatpak, and it doesn't make sense for us to duplicate something that already exists.  But we appreciate the idea anyway!

Something you might want to consider is waiting for one of the Free Fly events so you can see for yourself how the game runs before you buy anything.

I'm going to go ahead and close this issue.  I think you'll get more answers to your questions if you join either our Discord or Matrix channels, linked here: https://github.com/starcitizen-lug/information-howtos.  There are lots of Penguins active in there just waiting to help you out!

**Comment by the-sane** [comment]
Update:  To simplify the install process, the upcoming v1.14 of the LUG Helper will bundle the lutris install script and can launch Lutris and initiate the install process with one click.

**Comment by Gaming4LifeDE** [comment]
That's very nice. I think ease of use is one of the most important things to get people to view Linux as a good gaming platform and this is certainly a very good step in the direction. Thank you so much!

**Comment by mactan-sc** [comment]
with the tools available from [Open Wine Components](https://github.com/Open-Wine-Components) its become fairly straightforward to put together a flatpak of a game using proton. One such has been added to the wiki as one of the alternate install methods for star citizen

https://github.com/starcitizen-lug/knowledge-base/wiki/Alternative-Installations#flatpak
