### ISSUE TITLE
Alternative Workaround for Rudder devices

### ISSUE THREAD

**Issue by Priton-CE** [starcitizen-lug/information-howtos#9]
Currently the wiki features BeniWTVs excellent spoofing script.

On my device (Endeavour OS) the script stopped working (after switching from Manjaro). Found conditions on my system:
- The script can create a clone of my sticks
- The script cannot create a new device (event file in the filesystem) when cloning my Thrustmaster T-Rudder in _rudder mode_ (the reason for this is unknown). In _pedal mode_ it works fine (it does not get effected by the Reason explained below)

# Problem with the T-Rudder:
The event file
- does not have the same permissions as normal flight sticks (ACL for the user missing) (the reason why neither the script or other uinput software can detect it without changing the permissions or ACL by hand or adding the user to the `input` group)
- is classified as an Accelerometer (`udevadm info /dev/input/event<XYZ>`) (which is not an issue for the system but appears to be the reason why SC does not detect the Rudder)

# Reason:
udev classifies all devices with 3D Axis and no Keys as Accelerometers which also do not have universal access (ACL permissions so a user can access it)

# Solution (found by ngh)

**SPECIFIC TO THE THRUSTMASTER T-RUDDER. MODEL AND VENDOR ID NEED TO BE CHANGED FOR DIFFERENT DEVICES**

Add a rule to udev:
New file `/etc/udev/rules.d/90-thrustmaster-pedals-workaround.rules`
contents:
```
# the Thurstmaster T-Rudder gets detected as an accelerometer
ACTION=="add|change", KERNEL=="event[0-9]*", ENV{ID_VENDOR_ID}=="044f", ENV{ID_MODEL_ID}=="b679", ENV{ID_INPUT_ACCELEROMETER}="", ENV{ID_INPUT_JOYSTICK}="1", TAG+="uaccess"
```

This changes the device to be classified as a joystick and gives the device uaccess (the correct ACL so a user can access and read from it)

# Solution (with beniwtv's script)
Add yourself to the `input` group. This however is less then optimal.
Continue spoofing the device as described in the wiki.

**Comment by beniwtv** [comment]
Added to the wiki: https://github.com/starcitizen-lug/information-howtos/wiki/Tips-and-Tricks#rudder-pedals
